[package]
name = "guardian-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap = { version = "4.5", features = ["derive"] }
dunce.workspace = true
hex.workspace = true
ignore.workspace = true
once_cell.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls", "blocking"] }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
guardian-scan-policy.workspace = true

[dev-dependencies]
tempfile.workspace = true
